# Generated by Django 5.2.10 on 2026-03-05 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivelse')),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('doing', 'I gang'), ('paused', 'Pause'), ('testing', 'Test'), ('approval', 'Godkendelse'), ('complete', 'Færdig')], default='todo', max_length=20, verbose_name='Status')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Planlagt start')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='Planlagt slut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Opdateret')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Rækkefølge')),
                ('approvers', models.ManyToManyField(blank=True, related_name='approved_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Godkendere')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Tildelt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Oprettet af')),
            ],
            options={
                'verbose_name': 'Opgave',
                'verbose_name_plural': 'Opgaver',
                'ordering': ['planned_start', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Emne')),
                ('text', models.TextField(verbose_name='Tekst')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Opdateret')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_notes', to=settings.AUTH_USER_MODEL, verbose_name='Forfatter')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tasks.task', verbose_name='Opgave')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Noter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/attachments/%Y/%m/', verbose_name='Fil')),
                ('filename', models.CharField(max_length=255, verbose_name='Filnavn')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadet')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.tasknote', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Vedhæftet fil',
                'verbose_name_plural': 'Vedhæftede filer',
            },
        ),
        migrations.CreateModel(
            name='TaskStateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, choices=[('todo', 'Todo'), ('doing', 'I gang'), ('paused', 'Pause'), ('testing', 'Test'), ('approval', 'Godkendelse'), ('complete', 'Færdig')], max_length=20, verbose_name='Fra status')),
                ('to_state', models.CharField(choices=[('todo', 'Todo'), ('doing', 'I gang'), ('paused', 'Pause'), ('testing', 'Test'), ('approval', 'Godkendelse'), ('complete', 'Færdig')], max_length=20, verbose_name='Til status')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ændret')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_state_changes', to=settings.AUTH_USER_MODEL, verbose_name='Ændret af')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='tasks.task', verbose_name='Opgave')),
            ],
            options={
                'verbose_name': 'Statusændring',
                'verbose_name_plural': 'Statusændringer',
                'ordering': ['changed_at'],
            },
        ),
    ]
