# Generated by Django 5.2.10 on 2026-03-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='approvers',
        ),
        migrations.AddField(
            model_name='task',
            name='approvers',
            field=models.CharField(blank=True, help_text='Navne på godkendere, adskilt med komma', max_length=500, verbose_name='Godkendere'),
        ),
    ]
