# Generated by Django 5.2.10 on 2026-05-07 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('read', 'Læs'), ('write', 'Læs+skriv')], default='read', max_length=10, verbose_name='Adgang')),
                ('label', models.CharField(blank=True, default='', help_text="Til genkendelse — fx 'Claude MCP – laptop'", max_length=80, verbose_name='Etiket')),
                ('prefix', models.CharField(db_index=True, max_length=10, unique=True)),
                ('hashed_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Bruger')),
            ],
            options={
                'verbose_name': 'API-nøgle',
                'verbose_name_plural': 'API-nøgler',
                'ordering': ['-created_at'],
            },
        ),
    ]
