# Generated by Django 5.2.10 on 2026-02-11 21:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnCallDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2100)], verbose_name='År')),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)], verbose_name='Uge')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Noter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_duties', to=settings.AUTH_USER_MODEL, verbose_name='Medarbejder')),
            ],
            options={
                'verbose_name': 'Rådighedsvagt',
                'verbose_name_plural': 'Rådighedsvagter',
                'ordering': ['-year', '-week_number'],
                'indexes': [models.Index(fields=['-year', '-week_number'], name='oncall_onca_year_13c0a7_idx')],
                'unique_together': {('year', 'week_number')},
            },
        ),
    ]
