# Generated by Django 5.2.10 on 2026-07-03 11:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnCallChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2100)], verbose_name='År')),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)], verbose_name='Uge')),
                ('effective_at', models.DateTimeField(verbose_name='Gældende fra')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ændret')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oncall_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Ændret af')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oncall_changes_from', to=settings.AUTH_USER_MODEL, verbose_name='Fra')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oncall_changes_to', to=settings.AUTH_USER_MODEL, verbose_name='Til')),
            ],
            options={
                'verbose_name': 'Vagtændring',
                'verbose_name_plural': 'Vagtændringer',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['year', 'week_number'], name='oncall_onca_year_5a1d3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnCallSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2100)], verbose_name='År')),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)], verbose_name='Uge')),
                ('start_at', models.DateTimeField(verbose_name='Fra')),
                ('end_at', models.DateTimeField(verbose_name='Til')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_segments', to=settings.AUTH_USER_MODEL, verbose_name='Medarbejder')),
            ],
            options={
                'verbose_name': 'Vagtperiode',
                'verbose_name_plural': 'Vagtperioder',
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['year', 'week_number'], name='oncall_onca_year_eaa4af_idx'), models.Index(fields=['start_at', 'end_at'], name='oncall_onca_start_a_c38870_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='oncall_segment_ends_after_start')],
            },
        ),
    ]
