# Generated by Django 5.2.10 on 2026-02-01 14:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2100)], verbose_name='År')),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)], verbose_name='Uge')),
                ('helpdesk_new', models.PositiveIntegerField(default=0, help_text='Antal nye helpdesk-sager i ugen', verbose_name='Nye sager')),
                ('helpdesk_closed', models.PositiveIntegerField(default=0, help_text='Antal lukkede helpdesk-sager i ugen', verbose_name='Lukkede sager')),
                ('helpdesk_open', models.PositiveIntegerField(default=0, help_text='Samlet antal åbne sager ved ugens slutning', verbose_name='Åbne sager')),
                ('summary', models.TextField(blank=True, help_text='Kort beskrivelse af ugens vigtigste aktiviteter', verbose_name='Ugeoversigt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Opdateret')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weeklogs_created', to=settings.AUTH_USER_MODEL, verbose_name='Oprettet af')),
            ],
            options={
                'verbose_name': 'Ugelog',
                'verbose_name_plural': 'Ugelogs',
                'ordering': ['-year', '-week_number'],
            },
        ),
        migrations.CreateModel(
            name='PriorityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, help_text='Detaljeret beskrivelse af opgaven', verbose_name='Beskrivelse')),
                ('priority', models.CharField(choices=[('high', 'Høj'), ('medium', 'Medium'), ('low', 'Lav')], default='medium', max_length=10, verbose_name='Prioritet')),
                ('status', models.CharField(choices=[('not_started', 'Ikke startet'), ('ongoing', 'Igangværende'), ('blocked', 'Blokeret'), ('completed', 'Afsluttet')], default='not_started', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Eventuelle noter eller opdateringer', verbose_name='Noter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weeklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_items', to='logbook.weeklog', verbose_name='Ugelog')),
            ],
            options={
                'verbose_name': 'Prioriteret opgave',
                'verbose_name_plural': 'Prioriterede opgaver',
                'ordering': ['-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('incident_type', models.CharField(choices=[('security', 'Sikkerhed'), ('system', 'Systemfejl'), ('network', 'Netværk'), ('data', 'Data'), ('other', 'Andet')], default='other', max_length=20, verbose_name='Type')),
                ('severity', models.CharField(choices=[('critical', 'Kritisk'), ('high', 'Høj'), ('medium', 'Medium'), ('low', 'Lav')], default='medium', max_length=20, verbose_name='Alvorlighed')),
                ('description', models.TextField(help_text='Detaljeret beskrivelse af hændelsen', verbose_name='Beskrivelse')),
                ('resolution', models.TextField(blank=True, help_text='Hvordan blev hændelsen løst?', verbose_name='Løsning')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tidspunkt')),
                ('resolved', models.BooleanField(default=False, verbose_name='Løst')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weeklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='logbook.weeklog', verbose_name='Ugelog')),
            ],
            options={
                'verbose_name': 'Hændelse',
                'verbose_name_plural': 'Hændelser',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, verbose_name='Medarbejder')),
                ('absence_type', models.CharField(choices=[('vacation', 'Ferie'), ('sick', 'Sygdom'), ('course', 'Kursus'), ('meeting', 'Møde/Konference'), ('other', 'Andet')], default='vacation', max_length=20, verbose_name='Type')),
                ('start_date', models.DateField(verbose_name='Fra dato')),
                ('end_date', models.DateField(verbose_name='Til dato')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Noter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weeklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='logbook.weeklog', verbose_name='Ugelog')),
            ],
            options={
                'verbose_name': 'Fravær',
                'verbose_name_plural': 'Fravær',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklog',
            index=models.Index(fields=['-year', '-week_number'], name='logbook_wee_year_82c484_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklog',
            unique_together={('year', 'week_number')},
        ),
    ]
