# Generated by Django 5.2.10 on 2026-02-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('vacation', 'Ferie'), ('sick', 'Sygdom'), ('course', 'Kursus'), ('meeting', 'Møde/Konference'), ('flex', 'Flex fri'), ('other', 'Andet')], default='vacation', max_length=20, verbose_name='Type'),
        ),
    ]
