# Generated by Django 5.2.10 on 2026-02-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_alter_absence_absence_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['start_date'], 'verbose_name': 'Bemanding', 'verbose_name_plural': 'Bemanding'},
        ),
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('vacation', 'Ferie'), ('sick', 'Sygdom'), ('course', 'Kursus'), ('meeting', 'Møde/Konference'), ('flex', 'Flex fri'), ('wfh', 'Arbejder hjemme'), ('other', 'Andet')], default='vacation', max_length=20, verbose_name='Type'),
        ),
    ]
