# Generated by Django 5.2.10 on 2026-02-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_add_wfh_absence_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priorityitem',
            options={'ordering': ['order', '-priority', 'title'], 'verbose_name': 'Prioriteret opgave', 'verbose_name_plural': 'Prioriterede opgaver'},
        ),
        migrations.AddField(
            model_name='priorityitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Rækkefølge'),
        ),
    ]
