# Generated by Django 5.2.10 on 2026-02-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_alter_priorityitem_options_priorityitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklog',
            name='meeting_attendees',
            field=models.TextField(blank=True, help_text='Deltagere til mandagsmødet', verbose_name='Deltagere'),
        ),
        migrations.AddField(
            model_name='weeklog',
            name='meeting_minutes',
            field=models.TextField(blank=True, help_text='Referat af mandagsmødet', verbose_name='Referat'),
        ),
    ]
