# Generated by Django 5.2.10 on 2026-02-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_weeklog_meeting_attendees_weeklog_meeting_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklog',
            name='meeting_skipped',
            field=models.BooleanField(default=False, help_text='Angiv om mandagsmødet blev aflyst denne uge', verbose_name='Møde aflyst'),
        ),
        migrations.AddField(
            model_name='weeklog',
            name='meeting_skipped_reason',
            field=models.CharField(blank=True, help_text='Kort begrundelse for hvorfor mødet blev aflyst', max_length=200, verbose_name='Årsag til aflysning'),
        ),
    ]
