# Generated by Django 5.2.10 on 2026-03-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_meeting_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklog',
            name='meeting_attendees',
            field=models.TextField(blank=True, default='', help_text='Deltagere til mandagsmødet', verbose_name='Deltagere'),
        ),
        migrations.AlterField(
            model_name='weeklog',
            name='meeting_minutes',
            field=models.TextField(blank=True, default='', help_text='Referat af mandagsmødet', verbose_name='Referat'),
        ),
    ]
