# Generated by Django 5.2.10 on 2026-05-07 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_priority_item_appearances'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='priorityitem',
            new_name='logbook_pri_status_50da44_idx',
            old_name='logbook_pri_status_last_active_idx',
        ),
        migrations.RenameIndex(
            model_name='priorityitemappearance',
            new_name='logbook_pri_weeklog_18d10c_idx',
            old_name='logbook_pri_appear_week_order_idx',
        ),
        migrations.AddField(
            model_name='priorityitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Slettet'),
        ),
        migrations.AddField(
            model_name='priorityitem',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='logbook.priorityitem', verbose_name='Flettet ind i'),
        ),
        migrations.AlterField(
            model_name='priorityitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Generelle noter, der gælder hele opgavens livscyklus', verbose_name='Noter'),
        ),
        migrations.AlterField(
            model_name='priorityitemappearance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='priorityitem',
            index=models.Index(fields=['deleted_at'], name='logbook_pri_deleted_bf98e6_idx'),
        ),
    ]
