# Generated by Django 5.2.10 on 2026-06-18 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_priority_item_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Brugeren der oprettede hændelsen. NULL for rækker oprettet før 0.7.18.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_logged', to=settings.AUTH_USER_MODEL, verbose_name='Logget af'),
        ),
    ]
