# Generated by Django 5.2.10 on 2026-08-21 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0010_add_incident_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekLogSignoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Meldt klar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeklog_signoffs', to=settings.AUTH_USER_MODEL, verbose_name='Bruger')),
                ('weeklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoffs', to='logbook.weeklog', verbose_name='Ugelog')),
            ],
            options={
                'verbose_name': 'Klarmelding',
                'verbose_name_plural': 'Klarmeldinger',
                'ordering': ['created_at'],
                'unique_together': {('weeklog', 'user')},
            },
        ),
    ]
