# Generated by Django 5.2.10 on 2026-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0011_weeklogsignoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklog',
            name='helpdesk_open_0_7',
            field=models.PositiveIntegerField(default=0, help_text='Åbne sager med en liggetid på 0-7 dage', verbose_name='Åbne 0-7 dage'),
        ),
        migrations.AddField(
            model_name='weeklog',
            name='helpdesk_open_31_90',
            field=models.PositiveIntegerField(default=0, help_text='Åbne sager med en liggetid på 31-90 dage', verbose_name='Åbne 31-90 dage'),
        ),
        migrations.AddField(
            model_name='weeklog',
            name='helpdesk_open_8_30',
            field=models.PositiveIntegerField(default=0, help_text='Åbne sager med en liggetid på 8-30 dage', verbose_name='Åbne 8-30 dage'),
        ),
        migrations.AddField(
            model_name='weeklog',
            name='helpdesk_open_over_90',
            field=models.PositiveIntegerField(default=0, help_text='Åbne sager med en liggetid på over 90 dage', verbose_name='Åbne over 90 dage'),
        ),
    ]
