# Generated by Django 5.2.10 on 2026-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    """Re-cut the liggetid buckets from four to seven.

    The old 8-30 and over-90 counts are dropped rather than split: they
    only existed for the few hours 0.10.0 was live, and the ServiceDesk
    sync recomputes the current week's breakdown from scratch every five
    minutes. Weeks kept by hand simply show no breakdown until someone
    fills in the new fields.
    """

    dependencies = [
        ('logbook', '0012_weeklog_helpdesk_open_0_7_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklog',
            name='helpdesk_open_8_30',
        ),
        migrations.RemoveField(
            model_name='weeklog',
            name='helpdesk_open_over_90',
        ),
        migrations.AddField(
            model_name='weeklog',
            name='helpdesk_open_15_30',
            field=models.PositiveIntegerField(default=0, help_text='Åbne sager med en liggetid på 15-30 dage', verbose_name='Åbne 2 uger - 1 måned'),
        ),
        migrations.AddField(
            model_name='weeklog',
            name='helpdesk_open_181_365',
            field=models.PositiveIntegerField(default=0, help_text='Åbne sager med en liggetid på 181-365 dage', verbose_name='Åbne 6-12 måneder'),
        ),
        migrations.AddField(
            model_name='weeklog',
            name='helpdesk_open_8_14',
            field=models.PositiveIntegerField(default=0, help_text='Åbne sager med en liggetid på 8-14 dage', verbose_name='Åbne 1-2 uger'),
        ),
        migrations.AddField(
            model_name='weeklog',
            name='helpdesk_open_91_180',
            field=models.PositiveIntegerField(default=0, help_text='Åbne sager med en liggetid på 91-180 dage', verbose_name='Åbne 3-6 måneder'),
        ),
        migrations.AddField(
            model_name='weeklog',
            name='helpdesk_open_over_365',
            field=models.PositiveIntegerField(default=0, help_text='Åbne sager med en liggetid på over 365 dage', verbose_name='Åbne over 12 måneder'),
        ),
        migrations.AlterField(
            model_name='weeklog',
            name='helpdesk_open_0_7',
            field=models.PositiveIntegerField(default=0, help_text='Åbne sager med en liggetid på 0-7 dage', verbose_name='Åbne under 1 uge'),
        ),
        migrations.AlterField(
            model_name='weeklog',
            name='helpdesk_open_31_90',
            field=models.PositiveIntegerField(default=0, help_text='Åbne sager med en liggetid på 31-90 dage', verbose_name='Åbne 1-3 måneder'),
        ),
    ]
