# Generated by Django 5.2.10 on 2026-05-08 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, help_text='Hvad ønskes der? Hvorfor? Eventuelle links til GitHub-issues, Figma osv.', verbose_name='Beskrivelse')),
                ('category', models.CharField(choices=[('technical', 'Teknisk'), ('ui', 'UI / brugerflade'), ('integration', 'Integration'), ('bug', 'Fejl'), ('other', 'Andet')], default='other', max_length=20, verbose_name='Kategori')),
                ('importance', models.CharField(choices=[('low', 'Lav'), ('medium', 'Medium'), ('high', 'Høj'), ('critical', 'Kritisk')], default='medium', max_length=10, verbose_name='Vigtighed')),
                ('status', models.CharField(choices=[('open', 'Åben'), ('in_progress', 'I gang'), ('solved', 'Løst')], default='open', max_length=20, verbose_name='Status')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manuel sortering inden for kolonnen.', verbose_name='Rækkefølge')),
                ('solved_at', models.DateTimeField(blank=True, null=True, verbose_name='Løst')),
                ('resolution_notes', models.TextField(blank=True, help_text='Hvad endte vi med at gøre? Hvilken commit / pr / hvilken version?', verbose_name='Løsning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests_solved', to=settings.AUTH_USER_MODEL, verbose_name='Løst af')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Indsendt af')),
            ],
            options={
                'verbose_name': 'Feature-forslag',
                'verbose_name_plural': 'Feature-forslag',
                'ordering': ['status', 'order', '-created_at'],
                'indexes': [models.Index(fields=['status', 'order'], name='feedback_fe_status_e1b764_idx'), models.Index(fields=['category'], name='feedback_fe_categor_ee625a_idx')],
            },
        ),
    ]
