# Generated by Django 5.2.10 on 2026-05-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerequest',
            name='triggers_version_bump',
            field=models.BooleanField(default=False, help_text='Sæt sand hvis forslaget kræver et minor- eller major-bump af applikationen, ikke kun en patch. Bruges til at planlægge udgivelseskadencen.', verbose_name='Udløser version-bump'),
        ),
    ]
