# Generated by Django 5.2.10 on 2026-05-08 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Bruges som data-event på <html>. Skal matche CSS-reglerne.', max_length=40, unique=True, verbose_name='Slug')),
                ('name', models.CharField(help_text='Vises i tweaks-panelet og i admin.', max_length=80, verbose_name='Navn')),
                ('description', models.TextField(blank=True, help_text='Hvad gør temaet visuelt? Hvilken anledning?', verbose_name='Beskrivelse')),
                ('is_active', models.BooleanField(default=True, help_text='Inaktive temaer ignoreres af både skedule og bruger-pick.', verbose_name='Aktiv')),
                ('user_selectable', models.BooleanField(default=True, help_text='Hvis sand: dukker op i tweaks-panelets Tema-dropdown. Sæt falsk for et tema der kun bør køre på specifikke datoer.', verbose_name='Kan vælges af brugere')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temaer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start')),
                ('end_date', models.DateField(help_text='Inklusiv.', verbose_name='Slut')),
                ('label', models.CharField(blank=True, help_text="Fri tekst — fx 'Star Wars Day 2026' eller 'Julestemning uge 51-52'.", max_length=120, verbose_name='Etiket')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='themes.theme', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Tema-skedule',
                'verbose_name_plural': 'Tema-skeduler',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='themes_them_start_d_db8c54_idx')],
            },
        ),
    ]
