# Generated by Django 5.2.10 on 2026-05-08 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_seed_pirate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBannerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='En enkelt linje der dukker op i banneret. Holdes kort — banneret afkorter med ellipsis.', verbose_name='Tekst')),
                ('is_active', models.BooleanField(default=True, help_text='Inaktive beskeder ekskluderes fra rotationen uden at slette dem.', verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, help_text='Rækkefølge i admin. Påvirker ikke rotationen (den er tilfældig).', verbose_name='Sortering')),
                ('notes', models.CharField(blank=True, help_text='Editor-private kontekst (kilde, intern joke-forklaring osv.). Vises ikke i banneret.', max_length=200, verbose_name='Internt notat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_messages', to='themes.theme', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Banner-besked',
                'verbose_name_plural': 'Banner-beskeder',
                'ordering': ['theme', 'order', 'id'],
                'indexes': [models.Index(fields=['theme', 'is_active'], name='themes_them_theme_i_cc48f8_idx')],
            },
        ),
    ]
