# Generated by Django 5.2.10 on 2026-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_seed_banner_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeschedule',
            name='recurs_annually',
            field=models.BooleanField(default=False, help_text='Hvis sand: kun måned + dag betyder noget — temaet aktiveres samme datoer hvert år. Året i felterne ovenfor bruges kun som anker.', verbose_name='Gentages årligt'),
        ),
        migrations.AlterField(
            model_name='themeschedule',
            name='label',
            field=models.CharField(blank=True, help_text="Fri tekst — fx 'Star Wars Day' eller 'Julestemning uge 51-52'.", max_length=120, verbose_name='Etiket'),
        ),
    ]
